### ISSUE TITLE
Flag_builder の概要と実装について

### ISSUE THREAD

**Issue by r-kurose** [ShibauraRTM/Make_sounds_with_pressure_pkg#2]
RT コンポーネント操作マニュアルの3.2章には、変換式や変数 dt についての記述がありますが、
ソースコードの該当部分がわかりません。対応を教えて下さい。

**Comment by ShibauraRTM** [comment]
コンポーネントの更新が遅れていたようです，申し訳ございません． 
Flag_builder/src/flag_builder.cppにソースコードに該当する箇所があります．
https://github.com/ShibauraRTM/Make_sounds_with_pressure_pkg/blob/master/flag_builder/src/flag_builder.cpp


Windows 10 版のメールから送信

差出人: r-kurose
送信日時: 2019年12月2日 17:43
宛先: ShibauraRTM/Make_sounds_with_pressure_pkg
CC: Subscribed
件名: [ShibauraRTM/Make_sounds_with_pressure_pkg] Flag_builder の概要と実装について (#2)

RT コンポーネント操作マニュアルの3.2章には、変換式や変数 dt についての記述がありますが、
ソースコードの該当部分がわかりません。対応を教えて下さい。

**Comment by r-kurose** [comment]
対応がわかりました。
