### ISSUE TITLE
数式の記方について

### ISSUE THREAD

**Issue by r-kurose** [ShibauraRTM/Make_sounds_with_pressure_pkg#3]
RT コンポーネント操作マニュアルの 3.2 章に数式が記述されていますが、tan や sin が斜体になっています。
教科書などを見ればわかりますが、斜体は変数(x,y, ...)に使うのが一般的なのです。

参考 : x, y, θ は斜めですが、 sin は違います。
https://en.wikipedia.org/wiki/Sine

**Comment by ShibauraRTM** [comment]
マニュアルを修正致しました。
ご確認宜しくお願いします。

**Comment by r-kurose** [comment]
ありがとうございます。直っていました。
